/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cine;

/**
 *
 * @author nicolasmedina
 */
public class ConsultaDatos extends javax.swing.JFrame {
        LógicaCine cine = new LógicaCine();
        
        public int sillasocupadas;
        public int sillasocfil1=0;
        public int sillasocfil2=0;
        public int sillasocfil3=0;
        public int sillasocfil4=0;
        public int sillasocfil5=0;
        public int sillasocfil6=0;
        public int sillasocfil7=0;
        public int sillasocfil8=0;
        public int sillasocfil9=0;
        public int sillasocfil10=0;
        public int sillasocfil11=0;
        public int sillasocfil12=0;
        public int sillasocfil13=0;
        public int sillasocfil14=0;
        public int sillasocfil15=0;
    /**
     * Creates new form ConsultaDatos
     */
    public ConsultaDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        compradasfila = new javax.swing.JTextField();
        disponiblesfila = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        compradas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        disponibles = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dinero = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        filas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        filas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filasActionPerformed(evt);
            }
        });
        getContentPane().add(filas, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 152, 72, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consulta de Datos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 32, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione la fila");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 156, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Disponibilidad de sillas por fila");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 118, -1, -1));

        compradasfila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compradasfilaActionPerformed(evt);
            }
        });
        getContentPane().add(compradasfila, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 322, 97, 35));

        disponiblesfila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disponiblesfilaActionPerformed(evt);
            }
        });
        getContentPane().add(disponiblesfila, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 237, 97, 35));

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Compradas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Disponibles");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 217, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Disponibilidad de sillas en sala");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 118, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Disponibles");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 217, -1, -1));

        compradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compradasActionPerformed(evt);
            }
        });
        getContentPane().add(compradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 322, 97, 35));

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Compradas");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 300, -1, -1));

        disponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disponiblesActionPerformed(evt);
            }
        });
        getContentPane().add(disponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 239, 97, 35));

        jLabel9.setFont(new java.awt.Font("Lucida Bright", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Dinero de boletas vendidas");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 118, -1, -1));

        dinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dineroActionPerformed(evt);
            }
        });
        getContentPane().add(dinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 239, 136, 35));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Consultar precio de boletas por fila");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, -1, 50));

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, 40));

        jButton3.setText("Calcular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filasActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_filasActionPerformed

    private void compradasfilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compradasfilaActionPerformed
        // TODO add your handling code here:
        
            
    }//GEN-LAST:event_compradasfilaActionPerformed

    private void disponiblesfilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disponiblesfilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disponiblesfilaActionPerformed

    private void compradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compradasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_compradasActionPerformed

    private void disponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disponiblesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_disponiblesActionPerformed

    private void dineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dineroActionPerformed
        // TODO add your handling code here:
        dinero.setText(String.valueOf(cine.preciototal(cine.fila, cine.columna, cine.preciof1, cine.preciof2, cine.preciof3, cine.preciof4, cine.preciof5, cine.preciof6, cine.preciof7, cine.preciof8, cine.preciof9, cine.preciof10, cine.preciof11, cine.preciof12, cine.preciof13, cine.preciof14, cine.preciof15)));
    }//GEN-LAST:event_dineroActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        InterfazMenuCine abrir = new InterfazMenuCine();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ConsultaValorFila abrir = new ConsultaValorFila();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        disponibles.setText(String.valueOf(sillasocupadas));
        
        disponibles.setText(String.valueOf(450- sillasocupadas));
        
        //Compradas
        if(filas.getSelectedItem()=="1"){
            compradasfila.setText(String.valueOf(sillasocfil1)); 
        }
        else if(filas.getSelectedItem()=="2"){
            compradasfila.setText(String.valueOf(sillasocfil2)); 
        }
        else if(filas.getSelectedItem()=="3"){
            compradasfila.setText(String.valueOf(sillasocfil3)); 
        }
        else if(filas.getSelectedItem()=="4"){
            compradasfila.setText(String.valueOf(sillasocfil4)); 
        }
        else if(filas.getSelectedItem()=="5"){
            compradasfila.setText(String.valueOf(sillasocfil5)); 
        }
        else if(filas.getSelectedItem()=="6"){
            compradasfila.setText(String.valueOf(sillasocfil6)); 
        }
        else if(filas.getSelectedItem()=="7"){
            compradasfila.setText(String.valueOf(sillasocfil7)); 
        }
        else if(filas.getSelectedItem()=="8"){
            compradasfila.setText(String.valueOf(sillasocfil8)); 
        }
        else if(filas.getSelectedItem()=="9"){
            compradasfila.setText(String.valueOf(sillasocfil9)); 
        }
        else if(filas.getSelectedItem()=="10"){
            compradasfila.setText(String.valueOf(sillasocfil10)); 
        }
        else if(filas.getSelectedItem()=="11"){
            compradasfila.setText(String.valueOf(sillasocfil11)); 
        }
        else if(filas.getSelectedItem()=="12"){
            compradasfila.setText(String.valueOf(sillasocfil12)); 
        }
        else if(filas.getSelectedItem()=="13"){
            compradasfila.setText(String.valueOf(sillasocfil13)); 
        }
        else if(filas.getSelectedItem()=="14"){
            compradasfila.setText(String.valueOf(sillasocfil14)); 
        }
        else {
            compradasfila.setText(String.valueOf(sillasocfil15)); 
        }
    //Disponibles
        if(filas.getSelectedItem()=="1"){
            disponiblesfila.setText(String.valueOf(30 - sillasocfil1)); 
        }
        else if(filas.getSelectedItem()=="2"){
            disponiblesfila.setText(String.valueOf(30 - sillasocfil2)); 
        }
        else if(filas.getSelectedItem()=="3"){
            disponiblesfila.setText(String.valueOf(30 - sillasocfil3)); 
        }
        else if(filas.getSelectedItem()=="4"){
            disponiblesfila.setText(String.valueOf(30 - sillasocfil4)); 
        }
        else if(filas.getSelectedItem()=="5"){
            disponiblesfila.setText(String.valueOf(30 - sillasocfil5)); 
        }
        else if(filas.getSelectedItem()=="6"){
            disponiblesfila.setText(String.valueOf(30 - sillasocfil6)); 
        }
        else if(filas.getSelectedItem()=="7"){
            disponiblesfila.setText(String.valueOf(30 - sillasocfil7)); 
        }
        else if(filas.getSelectedItem()=="8"){
            disponiblesfila.setText(String.valueOf(30 - sillasocfil8)); 
        }
        else if(filas.getSelectedItem()=="9"){
            disponiblesfila.setText(String.valueOf(30 - sillasocfil9)); 
        }
        else if(filas.getSelectedItem()=="10"){
            disponiblesfila.setText(String.valueOf(30 - sillasocfil10)); 
        }
        else if(filas.getSelectedItem()=="11"){
            disponiblesfila.setText(String.valueOf(30 - sillasocfil11)); 
        }
        else if(filas.getSelectedItem()=="12"){
            disponiblesfila.setText(String.valueOf(30 - sillasocfil12)); 
        }
        else if(filas.getSelectedItem()=="13"){
            disponiblesfila.setText(String.valueOf(30 - sillasocfil13)); 
        }
        else if(filas.getSelectedItem()=="14"){
            disponiblesfila.setText(String.valueOf(30 - sillasocfil14)); 
        }
        else {
            disponiblesfila.setText(String.valueOf(30 - sillasocfil15)); 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField compradas;
    private javax.swing.JTextField compradasfila;
    private javax.swing.JTextField dinero;
    private javax.swing.JTextField disponibles;
    private javax.swing.JTextField disponiblesfila;
    private javax.swing.JComboBox<String> filas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
